title: d(evelop)er.com
email: d6er@qq.com
description: >
  Personal blog of a web developer.
baseurl: ""
url: "http://d6er.com"
twitter_username: d5per
github_username:  d6er

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: d6er

google_analytics: UA-58185705-1