title: d(evelop)er.com
email: y15e@qq.com
description: >
  Personal blog of a web developer.
baseurl: ""
url: "http://d6er.com"
twitter_username: d5per
github_username:  y15e

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: y15e

google_analytics: UA-58185705-1