title: blog.y15e.io
email: y15e@qq.com
description: >
  Development Blog
baseurl: ""
url: "https://blog.y15e.io"
twitter_username: y15e_
github_username: y15e

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: d6er

google_analytics: UA-58185705-1