title: y15e development blog

description: >
  Development Blog

url: "https://blog.y15e.io"

github_username: y15e

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: d6er

google_analytics: UA-58185705-1